### PR TITLE
backend implementation for read-only

### PR DESCRIPTION
**Pull request by fbiko**
Made a slight mistake in allocRound.ts line 31, I mistakenly deleted/removed statist

### CODE REVIEW

**Review by Ullebror — CHANGES_REQUESTED** [review]
You can make multiple commits and pushes to your branch before creating a pull request, and you can also make changes to it even when it is in a pull request. Usually, if you know there is a mistake, you should fix it before creating a pull request. But now that it is in a pull request, you should create a new commit where you add it back and push it to your branch. 

Also, you have restricted copying a read-only allocation. Wasn't the idea of the read-only allocation exactly that it would be possible to copy, but nothing else could be done to it? From the card in trello: "Both read-only and normal can be used as source of making new copies."

**Comment by fbiko** [comment]
> You can make multiple commits and pushes to your branch before creating a pull request, and you can also make changes to it even when it is in a pull request. Usually, if you know there is a mistake, you should fix it before creating a pull request. But now that it is in a pull request, you should create a new commit where you add it back and push it to your branch.
> 
> Also, you have restricted copying a read-only allocation. Wasn't the idea of the read-only allocation exactly that it would be possible to copy, but nothing else could be done to it? From the card in trello: "Both read-only and normal can be used as source of making new copies."

You're right about the read-only allocation. I will make adjustments and commit. Thank you for the clarification.

**Review by Ullebror — COMMENTED** [review]
Sorry to do this in parts, but now I noticed that I get an error in the rest tests: ER_BAD_FIELD_ERROR. So these changes have not been made to the database yet and the tests don't work, since the database table does not have a column isReadOnly.

If it would affect only the tests, I think this would be fine to merge, but the Allocation page in the tool also breaks and gives that error.

**Review by alexonthespot7 — APPROVED** [review]
Looks good

**Review by alexonthespot7 — APPROVED** [review]
Good

**Review by Ullebror — APPROVED** [review]

**Pull request merged**
