### PR TITLE
date made more readble in timestamp format by adding - in between

### PR DESCRIPTION
**Pull request by mishrasur7**

### CODE REVIEW

**Comment by mishrasur7** [comment]
In addition to the above, I did format the transport for error log to look like the same as others.

**Review by valju — COMMENTED** [review]
Hmm. I have made the message condensed on purpose. So that even with not so wide console we would get fast to the real message. If ask me, I would keep the current. Logs we anyway look a lot while developing, and then the date is not even looked at, as the time is the only changing one.

So I would say, let's keep it, ok?

**Comment by mishrasur7** [comment]
Its perfectly ok Juhani.

**Comment by valju** [comment]
Trying the "Close pull-request feature" without committing the changes.

**Pull request closed without merging**
